<a href="https://colab.research.google.com/github/Ranjan-Segu/LogicMojo-AI-ML-April26-Ranjan_Segu/blob/main/Assignment_Numpy_%2B_Pandas_Logicmojo_Apr_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
# Question: Stack arrays a and b vertically
# input: a = np.arange(10).reshape(2,-1)
#        b = np.repeat(1, 10).reshape(2,-1)

In [2]:
import numpy as np

In [3]:
a = np.arange(10).reshape(2,-1)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
b = np.repeat(1, 10).reshape(2,-1)
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
c = np.vstack([a,b])
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [8]:
c = np.concatenate([a,b], axis = 1)
c

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [11]:
### reverse an array

arr = np.array([1, 2, 3, 6, 4, 5])
arr[::-1]

array([5, 4, 6, 3, 2, 1])

In [13]:
# Question: Get all items between 5 and 10 from a.

# Input: a = np.array([2, 6, 1, 9, 10, 3, 27])

a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a>5) & (a<10)]

array([6, 9])

In [ ]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a>5) & (a<10)]

array([6, 9])

In [15]:
# Find the maximum value from both of these array

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

In [16]:
print(max(b.max(),a.max()))

9

In [17]:
import pandas as pd

In [18]:
df = pd.DataFrame({'name': ['Vinay', 'Kushal', 'Aman', 'Saif'], 'age': [22, 25, 24,
28], 'occupation': ['engineer', 'doctor', 'data analyst', 'teacher']})

In [19]:
df

     name  age    occupation
0   Vinay   22      engineer
1  Kushal   25        doctor
2    Aman   24  data analyst
3    Saif   28       teacher

In [24]:
df.head()

     name  age    occupation
0   Vinay   22      engineer
1  Kushal   25        doctor
2    Aman   24  data analyst
3    Saif   28       teacher

In [20]:
df.columns

Index(['name', 'age', 'occupation'], dtype='object')

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        4 non-null      object
 1   age         4 non-null      int64
 2   occupation  4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

In [23]:
df.describe()

         age
count   4.00
mean   24.75
std     2.50
min    22.00
25%    23.50
50%    24.50
75%    25.75
max    28.00

In [25]:
df['age']

0    22
1    25
2    24
3    28
Name: age, dtype: int64

In [26]:
df.age

0    22
1    25
2    24
3    28
Name: age, dtype: int64

In [27]:
df[['age','name']]

   age    name
0   22   Vinay
1   25  Kushal
2   24    Aman
3   28    Saif

In [28]:
df[1:3]

     name  age    occupation
1  Kushal   25        doctor
2    Aman   24  data analyst

In [29]:
df[2::2]

   name  age    occupation
2  Aman   24  data analyst

In [30]:
df[::2]

    name  age    occupation
0  Vinay   22      engineer
2   Aman   24  data analyst

In [31]:
### Index based slicing

df.iloc[2,2]

'data analyst'

In [33]:
df['occupation'][2]

'data analyst'

In [34]:
df.iloc[3]

name             Saif
age                28
occupation    teacher
Name: 3, dtype: object

In [35]:
df

     name  age    occupation
0   Vinay   22      engineer
1  Kushal   25        doctor
2    Aman   24  data analyst
3    Saif   28       teacher

In [36]:
df.iloc[2,1:2]

age    24
Name: 2, dtype: object

In [37]:
df.iloc[[1,2,3]]

     name  age    occupation
1  Kushal   25        doctor
2    Aman   24  data analyst
3    Saif   28       teacher

In [38]:
df.iloc[1:3,0:3]

     name  age    occupation
1  Kushal   25        doctor
2    Aman   24  data analyst

In [39]:
print(df.loc[2,'age'])

24

In [40]:
df.loc[3]

name             Saif
age                28
occupation    teacher
Name: 3, dtype: object

In [41]:
df.loc[:,'name':'occupation'] #inclusivity in labels

     name  age    occupation
0   Vinay   22      engineer
1  Kushal   25        doctor
2    Aman   24  data analyst
3    Saif   28       teacher

In [42]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [43]:
df = pd.read_csv('/content/drive/MyDrive/BikeIndia.csv')
df.head()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,01-01-2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985
1,2,02-01-2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801
2,3,03-01-2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
3,4,04-01-2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
4,5,05-01-2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600

In [45]:
## Create a df from the above df which has only numerical columns

df2 = df.select_dtypes(include=['int64','float64'])
df2 = df2.loc[:,'temp':'cnt']
df2.head()

        temp     atemp      hum  windspeed  casual  registered   cnt
0  14.110847  18.18125  80.5833  10.749882     331         654   985
1  14.902598  17.68695  69.6087  16.652113     131         670   801
2   8.050924   9.47025  43.7273  16.636703     120        1229  1349
3   8.200000  10.60610  59.0435  10.739832     108        1454  1562
4   9.305237  11.46350  43.6957  12.522300      82        1518  1600

In [46]:
### drop duplicates based on temp
df2.drop_duplicates(subset = 'temp')

          temp     atemp      hum  windspeed  casual  registered   cnt
0    14.110847  18.18125  80.5833  10.749882     331         654   985
1    14.902598  17.68695  69.6087  16.652113     131         670   801
2     8.050924   9.47025  43.7273  16.636703     120        1229  1349
3     8.200000  10.60610  59.0435  10.739832     108        1454  1562
4     9.305237  11.46350  43.6957  12.522300      82        1518  1600
..         ...       ...      ...        ...     ...         ...   ...
718  13.530000  16.76085  66.7917   8.875021     314        3814  4128
722   9.483464  12.94500  79.1304   5.174437     174         746   920
723  11.943464  14.72325  73.4783  11.304642     440         573  1013
726  10.386653  12.75230  59.0000  10.416557     644        2451  3095
729   8.849153  11.17435  57.7500  10.374682     439        2290  2729

[498 rows x 7 columns]

In [47]:
#### Sort this new df based on temp asc order and humidity desc order

df2.sort_values(by=['temp','hum'], ascending=[True,False])

          temp      atemp      hum  windspeed  casual  registered   cnt
21    2.424346   3.953480  40.0000  11.521990      93         888   981
22    3.957390   4.941955  43.6522  16.522200     150         836   986
23    3.993043   5.896500  49.1739  10.608110      86        1330  1416
368   4.407500   5.966850  41.4583  12.374900      95        2273  2368
407   5.227500   5.082900  46.4583  27.417204      73        1456  1529
..         ...        ...      ...        ...     ...         ...   ...
544  34.200847  39.330650  48.8750  11.082939     829        4634  5463
209  34.371653  39.298350  54.2500  11.667246     670        3176  3846
202  34.781653  42.044800  58.0417   8.917700     562        2825  3387
203  34.815847  40.214350  50.0000   8.791807     987        2298  3285
552  35.328347  40.245650  49.2083  10.958118    1448        3392  4840

[730 rows x 7 columns]

In [48]:
#### Find the avg temp of the df

df2['temp'].mean()

np.float64(20.319259216986303)

In [49]:
#### Find the values of top 3 humidity values
df2.nlargest(3,'hum')

          temp     atemp      hum  windspeed  casual  registered   cnt
265  24.975847  26.10625  97.2500   5.250569     258        2137  2395
340  16.810000  20.01230  97.0417  17.833725      50         655   705
325  17.083347  21.08480  96.2500   7.959064      69        1538  1607

In [50]:
### Find the avg temp per season

df.head()

df.groupby('season')['temp'].agg(['mean','max'])

             mean        max
season
1       12.197035  23.472500
2       22.320611  33.141653
3       28.958682  35.328347
4       17.339148  26.957500

In [51]:
df.groupby(['season','mnth'])['temp'].mean()

season  mnth
1       1        9.694201
        2       12.235249
        3       16.012501
        12      12.215995
2       3       16.011340
        4       19.269952
        5       24.386735
        6       27.164208
3       6       29.815540
        7       30.974287
        8       29.051844
        9       25.597755
4       9       24.390739
        10      19.885500
        11      15.138010
        12      13.873371
Name: temp, dtype: float64

In [52]:
#### What are different values of weekday column

df['weekday'].value_counts().sort_index()

weekday
0    105
1    105
2    104
3    103
4    104
5    104
6    105
Name: count, dtype: int64

In [53]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [54]:
df.head(20)

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,01-01-2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985
1,2,02-01-2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801
2,3,03-01-2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
3,4,04-01-2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
4,5,05-01-2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600
5,6,06-01-2018,1,0,1,0,4,1,1,8.378268,11.66045,51.8261,6.000868,88,1518,1606
6,7,07-01-2018,1,0,1,0,5,1,2,8.057402,10.44195,49.8696,11.304642,148,1362,1510
7,8,08-01-2018,1,0,1,0,6,0,2,6.765000,8.11270,53.5833,17.875868,68,891,959
8,9,09-01-2018,1,0,1,0,0,0,1,5.671653,5.80875,43.4167,24.250650,54,768,822
9,10,10-01-2018,1,0,1,0,1,1,1,6.184153,7.54440,48.2917,14.958889,41,1280,1321
10,11,11-01-2018,1,0,1,0,2,1,2,6.932731,9.57320,68.6364,8.182844,43,1220,1263
11,12,12-01-2018,1,0,1,0,3,1,1,7.081807,8.02365,59.9545,20.410009,25,1137,1162
12,13,13-01-2018,1,0,1,0,4,1,1,6.765000,7.54415,47.0417,20.167000,38,1368,1406
13,14,14-01-2018,1,0,1,0,5,1,1,6.595670,9.42065,53.7826,8.478716,54,1367,1421
14,15,15-01-2018,1,0,1,0,6,0,2,9.566653,12.40560,49.8750,10.583521,222,1026,1248
15,16,16-01-2018,1,0,1,0,0,0,1,9.498347,11.71085,48.3750,12.625011,251,953,1204
16,17,17-01-2018,1,0,1,1,1,0,2,7.209153,8.83855,53.7500,12.999139,117,883,1000
17,18,18-01-2018,1,0,1,0,2,1,2,8.883347,11.61665,86.1667,9.833925,9,674,683
18,19,19-01-2018,1,0,1,0,3,1,2,11.979134,14.92110,74.1739,13.957239,78,1572,1650
19,20,20-01-2018,1,0,1,0,4,1,2,10.728347,12.75250,53.8333,13.125568,83,1844,1927

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     730 non-null    int64
 1   dteday      730 non-null    object
 2   season      730 non-null    int64
 3   yr          730 non-null    int64
 4   mnth        730 non-null    int64
 5   holiday     730 non-null    int64
 6   weekday     730 non-null    int64
 7   workingday  730 non-null    int64
 8   weathersit  730 non-null    int64
 9   temp        730 non-null    float64
 10  atemp       730 non-null    float64
 11  hum         730 non-null    float64
 12  windspeed   730 non-null    float64
 13  casual      730 non-null    int64
 14  registered  730 non-null    int64
 15  cnt         730 non-null    int64
dtypes: float64(4), int64(11), object(1)
memory usage: 91.4+ KB

In [56]:
df.describe()

,instant,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
count,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000
mean,365.500000,2.498630,0.500000,6.526027,0.028767,2.997260,0.683562,1.394521,20.319259,23.726322,62.765175,12.763620,849.249315,3658.757534,4508.006849
std,210.877136,1.110184,0.500343,3.450215,0.167266,2.006161,0.465405,0.544807,7.506729,8.150308,14.237589,5.195841,686.479875,1559.758728,1936.011647
min,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,2.424346,3.953480,0.000000,1.500244,2.000000,20.000000,22.000000
25%,183.250000,2.000000,0.000000,4.000000,0.000000,1.000000,0.000000,1.000000,13.811885,16.889713,52.000000,9.041650,316.250000,2502.250000,3169.750000
50%,365.500000,3.000000,0.500000,7.000000,0.000000,3.000000,1.000000,1.000000,20.465826,24.368225,62.625000,12.125325,717.000000,3664.500000,4548.500000
75%,547.750000,3.000000,1.000000,10.000000,0.000000,5.000000,1.000000,2.000000,26.880615,30.445775,72.989575,15.625589,1096.500000,4783.250000,5966.000000
max,730.000000,4.000000,1.000000,12.000000,1.000000,6.000000,1.000000,3.000000,35.328347,42.044800,97.250000,34.000021,3410.000000,6946.000000,8714.000000

In [57]:
type(df[['yr']])

pandas.core.frame.DataFrame

In [58]:
df.loc[2:6, ['windspeed','registered']]

   windspeed  registered
2  16.636703        1229
3  10.739832        1454
4  12.522300        1518
5   6.000868        1518
6  11.304642        1362

In [59]:
df.set_index('instant',inplace = True)
df.head()

,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
instant,,,,,,,,,,,,,,,
1,01-01-2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985
2,02-01-2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801
3,03-01-2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
4,04-01-2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
5,05-01-2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600

In [60]:
df.loc[2:6, ['windspeed','registered']]

         windspeed  registered
instant
2        16.652113         670
3        16.636703        1229
4        10.739832        1454
5        12.522300        1518
6         6.000868        1518

In [61]:
df.reset_index()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,01-01-2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985
1,2,02-01-2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801
2,3,03-01-2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
3,4,04-01-2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
4,5,05-01-2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,726,27-12-2019,1,1,12,0,4,1,2,10.420847,11.33210,65.2917,23.458911,247,1867,2114
726,727,28-12-2019,1,1,12,0,5,1,2,10.386653,12.75230,59.0000,10.416557,644,2451,3095
727,728,29-12-2019,1,1,12,0,6,0,2,10.386653,12.12000,75.2917,8.333661,159,1182,1341
728,729,30-12-2019,1,1,12,0,0,0,1,10.489153,11.58500,48.3333,23.500518,364,1432,1796
729,730,31-12-2019,1,1,12,0,1,1,2,8.849153,11.17435,57.7500,10.374682,439,2290,2729

In [62]:
df[0:1]

,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
instant,,,,,,,,,,,,,,,
1,01-01-2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985

In [63]:
df2 = df[df['windspeed']>10][['windspeed','atemp','temp']]
df2.head()

         windspeed     atemp       temp
instant
1        10.749882  18.18125  14.110847
2        16.652113  17.68695  14.902598
3        16.636703   9.47025   8.050924
4        10.739832  10.60610   8.200000
5        12.522300  11.46350   9.305237

In [64]:
df2.shape

(488, 3)

In [65]:
df.shape

(730, 15)

In [66]:
## merge the 2 datasets


df3 = pd.merge(df,df2, how = 'left', on = ['temp','atemp'])

df3.shape

(730, 16)

In [67]:
df3.head()

,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed_x,casual,registered,cnt,windspeed_y
0,01-01-2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985,10.749882
1,02-01-2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801,16.652113
2,03-01-2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349,16.636703
3,04-01-2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562,10.739832
4,05-01-2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600,12.522300

In [69]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   dteday       730 non-null    object
 1   season       730 non-null    int64
 2   yr           730 non-null    int64
 3   mnth         730 non-null    int64
 4   holiday      730 non-null    int64
 5   weekday      730 non-null    int64
 6   workingday   730 non-null    int64
 7   weathersit   730 non-null    int64
 8   temp         730 non-null    float64
 9   atemp        730 non-null    float64
 10  hum          730 non-null    float64
 11  windspeed_x  730 non-null    float64
 12  casual       730 non-null    int64
 13  registered   730 non-null    int64
 14  cnt          730 non-null    int64
 15  windspeed_y  489 non-null    float64
dtypes: float64(5), int64(10), object(1)
memory usage: 91.4+ KB

In [70]:
df4 = pd.concat([df,df2], axis = 0 )

In [71]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1218 entries, 1 to 730
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   dteday      730 non-null    object
 1   season      730 non-null    float64
 2   yr          730 non-null    float64
 3   mnth        730 non-null    float64
 4   holiday     730 non-null    float64
 5   weekday     730 non-null    float64
 6   workingday  730 non-null    float64
 7   weathersit  730 non-null    float64
 8   temp        1218 non-null   float64
 9   atemp       1218 non-null   float64
 10  hum         730 non-null    float64
 11  windspeed   1218 non-null   float64
 12  casual      730 non-null    float64
 13  registered  730 non-null    float64
 14  cnt         730 non-null    float64
dtypes: float64(14), object(1)
memory usage: 152.2+ KB

In [72]:
df['count_2'] = df['cnt'].apply(lambda x : x * 2)
df.head()

,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt,count_2
instant,,,,,,,,,,,,,,,,
1,01-01-2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985,1970
2,02-01-2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801,1602
3,03-01-2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349,2698
4,04-01-2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562,3124
5,05-01-2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600,3200

In [73]:
df['surrogate'] = df['dteday'].astype('str') + ": " + df['cnt'].astype('str')
df.head()

,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt,count_2,surrogate
instant,,,,,,,,,,,,,,,,,
1,01-01-2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985,1970,01-01-2018: 985
2,02-01-2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801,1602,02-01-2018: 801
3,03-01-2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349,2698,03-01-2018: 1349
4,04-01-2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562,3124,04-01-2018: 1562
5,05-01-2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600,3200,05-01-2018: 1600

In [74]:
df.describe().columns

Index(['season', 'yr', 'mnth', 'holiday', 'weekday', 'workingday',
       'weathersit', 'temp', 'atemp', 'hum', 'windspeed', 'casual',
       'registered', 'cnt', 'count_2'],
      dtype='object')

In [75]:
df5 = df[['temp', 'atemp', 'hum', 'windspeed', 'casual',
       'registered', 'cnt']]
df5.head()

              temp     atemp      hum  windspeed  casual  registered   cnt
instant
1        14.110847  18.18125  80.5833  10.749882     331         654   985
2        14.902598  17.68695  69.6087  16.652113     131         670   801
3         8.050924   9.47025  43.7273  16.636703     120        1229  1349
4         8.200000  10.60610  59.0435  10.739832     108        1454  1562
5         9.305237  11.46350  43.6957  12.522300      82        1518  1600

In [76]:
df.drop(['count_2','surrogate'], axis = 1, inplace = True)
df.head()

,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
instant,,,,,,,,,,,,,,,
1,01-01-2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985
2,02-01-2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801
3,03-01-2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
4,04-01-2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
5,05-01-2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600

In [77]:
df5.corr()

,temp,atemp,hum,windspeed,casual,registered,cnt
temp,1.000000,0.991696,0.128565,-0.158186,0.542731,0.539436,0.627044
atemp,0.991696,1.000000,0.141512,-0.183876,0.543362,0.543678,0.630685
hum,0.128565,0.141512,1.000000,-0.248506,-0.075211,-0.089212,-0.098543
windspeed,-0.158186,-0.183876,-0.248506,1.000000,-0.167995,-0.217914,-0.235132
casual,0.542731,0.543362,-0.075211,-0.167995,1.000000,0.394137,0.672123
registered,0.539436,0.543678,-0.089212,-0.217914,0.394137,1.000000,0.945411
cnt,0.627044,0.630685,-0.098543,-0.235132,0.672123,0.945411,1.000000

In [78]:
len(df5['temp'].unique())

498

In [79]:
df5['temp'].shape

(730,)

In [80]:
df['temp'].quantile(0.15)

np.float64(11.621279849999999)

In [81]:
df['temp'].describe()

count    730.000000
mean      20.319259
std        7.506729
min        2.424346
25%       13.811885
50%       20.465826
75%       26.880615
max       35.328347
Name: temp, dtype: float64

In [82]:
df3.isnull().sum()

dteday           0
season           0
yr               0
mnth             0
holiday          0
weekday          0
workingday       0
weathersit       0
temp             0
atemp            0
hum              0
windspeed_x      0
casual           0
registered       0
cnt              0
windspeed_y    241
dtype: int64

In [83]:
df3.isnull().sum()/len(df3) <0.3

dteday          True
season          True
yr              True
mnth            True
holiday         True
weekday         True
workingday      True
weathersit      True
temp            True
atemp           True
hum             True
windspeed_x     True
casual          True
registered      True
cnt             True
windspeed_y    False
dtype: bool

In [84]:
df3['windspeed_y'].fillna (df.windspeed.mean(), inplace= True)
df3.isnull().sum()

/tmp/ipykernel_1163/392708658.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df3['windspeed_y'].fillna (df.windspeed.mean(), inplace= True)

dteday         0
season         0
yr             0
mnth           0
holiday        0
weekday        0
workingday     0
weathersit     0
temp           0
atemp          0
hum            0
windspeed_x    0
casual         0
registered     0
cnt            0
windspeed_y    0
dtype: int64

In [85]:
import numpy as np

In [86]:
df[~np.isnan(df['temp'])].shape

(730, 15)

In [87]:
df6 = df.drop_duplicates(['temp'])
df6.shape

(498, 15)

In [88]:
df7 = df
df7.shape

(730, 15)

In [89]:
df7.drop('temp', axis = 1, inplace = True )

In [90]:
df.columns

Index(['dteday', 'season', 'yr', 'mnth', 'holiday', 'weekday', 'workingday',
       'weathersit', 'atemp', 'hum', 'windspeed', 'casual', 'registered',
       'cnt'],
      dtype='object')